#server:
#    port: 8087
#db:
#    name: crm
#spring:
#    datasource:
#        cj:
#driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5433/${db.name}
#        username: postgres
#        password: admin
#    jpa:
#        properties:
#            hibernate:
#                default_schema: crm
#                ddl-auto: update


