apiVersion: v1
kind: Service
metadata:
  name: customermanagement
  namespace: customermanagement
  labels:
    app: customermanagement
spec:
  ports:
  - name: https
    port: 3333
    targetPort: 3333
  selector:
    app: customermmanagement

