apiVersion: v1
kind: Service
metadata:
  name: customermanagement
  namespace: customermanagement
  labels:
    app: customermanagement
spec:
  ports:
  - name: https
    port: 8080
    targetPort: 8080
  selector:
    app: customermmanagement

